{% set name = "jhsingle-native-proxy" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('_', '-') }}/{{ name }}-{{ version }}.tar.gz
  sha256: 685f33b98e6ac747ca5d52484d046fb0dd0b91dfc6e2e0273470a058b31afac1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - jhsingle-native-proxy = jhsingle_native_proxy.main:run

requirements:
  host:
    - pip
    - python >=3.6.0,<4.0.0
  run:
    - python >=3.6.0,<4.0.0
    - jupyterhub >=1.0.0
    - tornado >=5.1
    - click >=7.0
    - aiohttp
    - simpervisor

test:
  imports:
    - jhsingle_native_proxy
  commands:
    - jhsingle-native-proxy --help

about:
  home: https://github.com/ideonate/jhsingle-native-proxy
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - LICENSE-jupyter-server-proxy
  summary: Wrap an arbitrary webapp so it can be used in place of jupyter-singleuser in a JupyterHub setting

extra:
  recipe-maintainers:
    - danlester
    - fcollonval
